export const allProducts = [
  {
    id: "fly-ash",
    name: "Fly Ash Bricks",
    desc: "High compressive strength, uniform size. Ideal for load-bearing walls in residential and commercial buildings.",
    specs: { Size: "230×110×75mm", Strength: "M7.5 – M10", Absorption: "< 12%", Finish: "Smooth" },
    gradient: "from-slate-700 to-slate-900",
    badge: "Best Seller",
    image: "/images/suksh-bricks-branded.jpg",
  },
  {
    id: "pavers",
    name: "Paver Blocks",
    desc: "Heavy-duty interlocking pavers for driveways, pavements, and parking areas. High durability.",
    specs: { Size: "200×100×60mm", Strength: "M30 Grade", Pattern: "Interlocking", Finish: "Textured" },
    gradient: "from-blue-800 to-blue-950",
    badge: "Popular",
    image: "/images/pavers-pattern.jpg",
  },
  {
    id: "tiles",
    name: "Parking Tiles",
    desc: "Elegant and durable tiles designed for parking lots and heavy-traffic areas.",
    specs: { Size: "300×300mm", Strength: "M35 Grade", Absorption: "< 5%", Finish: "Anti-Skid" },
    gradient: "from-gray-700 to-gray-900",
    badge: undefined,
    image: "/images/parking-tiles-dark.jpg",
  },
  {
    id: "kerb",
    name: "Kerb Stones",
    desc: "Road-grade kerb stones for traffic demarcation and road safety.",
    specs: { Size: "500×150×250mm", Strength: "M25 Grade", Type: "Road Grade", Finish: "Smooth" },
    gradient: "from-slate-600 to-slate-800",
    badge: undefined,
    image: "/images/paver-road.jpg",
  },
  {
    id: "hollow",
    name: "Hollow Blocks",
    desc: "Lightweight hollow concrete blocks for partition walls and non-load-bearing structures.",
    specs: { Size: "400×200×200mm", Strength: "M5 Grade", Weight: "Lightweight", Finish: "Textured" },
    gradient: "from-blue-700 to-blue-900",
    badge: undefined,
    image: "/images/parking-tiles-grey.jpg",
  },
  {
    id: "solid",
    name: "Solid Blocks",
    desc: "Industrial-grade solid concrete blocks with superior load-bearing capacity.",
    specs: { Size: "400×200×200mm", Strength: "M10 Grade", Type: "Load Bearing", Finish: "Smooth" },
    gradient: "from-gray-600 to-gray-800",
    badge: undefined,
    image: "/images/paver-project-driveway.jpg",
  },
  {
    id: "zigzag",
    name: "Zigzag Pavers",
    desc: "Interlocking zigzag design pavers available in grey and red. Perfect for walkways and garden paths.",
    specs: { Size: "200×160×60mm", Strength: "M30 Grade", Pattern: "Zigzag", Finish: "Textured" },
    gradient: "from-green-700 to-green-900",
    badge: "New",
    image: "/images/zigzag-pavers.jpg",
  },
];

export const galleryImages = [
  { id: 1, title: "Interlocking Paver Pattern", category: "Products", image: "/images/pavers-pattern.jpg" },
  { id: 2, title: "Paver Block Road", category: "Projects", image: "/images/paver-road.jpg" },
  { id: 3, title: "Herringbone Walkway", category: "Projects", image: "/images/pavers-herringbone.jpg" },
  { id: 4, title: "Dark Textured Pavers", category: "Products", image: "/images/parking-tiles-dark.jpg" },
  { id: 5, title: "Checkerboard Parking Tiles", category: "Products", image: "/images/parking-tiles-grey.jpg" },
  { id: 6, title: "Zigzag Interlocking Pavers", category: "Products", image: "/images/zigzag-pavers.jpg" },
  { id: 7, title: "Driveway Paver Project", category: "Projects", image: "/images/paver-project-driveway.jpg" },
  { id: 8, title: "Herringbone Closeup", category: "Production", image: "/images/pavers-herringbone-closeup.jpg" },
  { id: 9, title: "Grey Zigzag Pavers", category: "Products", image: "/images/zigzag-grey.jpg" },
  { id: 10, title: "Dark Zigzag Interlocking", category: "Production", image: "/images/zigzag-dark.jpg" },
  { id: 11, title: "Zigzag Pattern Road", category: "Projects", image: "/images/zigzag-pattern-road.jpg" },
  { id: 12, title: "Brick Delivery — Crane Loading", category: "Production", image: "/images/brick-delivery-truck.jpg" },
  { id: 13, title: "Brick Stacks — Yard Storage", category: "Production", image: "/images/brick-stacks-yard.jpg" },
  { id: 14, title: "SUKSH Branded Bricks", category: "Production", image: "/images/suksh-bricks-branded.jpg" },
  { id: 15, title: "Quality Check — Workers", category: "Production", image: "/images/suksh-bricks-workers.jpg" },
  { id: 16, title: "Factory Interior", category: "Production", image: "/images/suksh-factory-interior.jpg" },
];
